version: 2

updates:
  - package-ecosystem: "npm"
    directories:
      - "backend"
      - "frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependabot"
    assignees:
      - "kishieel"
    reviewers:
      - "kishieel"

  - package-ecosystem: docker
    directories:
      - "backend"
      - "frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependabot"
    assignees:
      - "kishieel"
    reviewers:
      - "kishieel"
