version: 2

updates:
  - package-ecosystem: "npm"
    directories:
      - "backend"
      - "frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependabot"
    assignees:
      - "kishieel"
    reviewers:
      - "kishieel"
    groups:
      deps-dev:
        dependency-type: "development"
      deps:
        dependency-type: "production"

  - package-ecosystem: docker
    directories:
      - "backend"
      - "frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependabot"
    assignees:
      - "kishieel"
    reviewers:
      - "kishieel"
    groups:
      docker:
        patterns:
          - "*"

