name: Build and push image
description: Build and push Docker image to GitHub Container Registry

inputs:
  registry:
    description: 'Container registry'
    required: true
    default: 'ghcr.io'
  image_name:
    description: 'Docker image name'
    required: true
  github_token:
    description: 'GitHub token'
    required: true
  context:
    description: 'Build context (backend or frontend)'
    required: true

outputs:
  image:
    description: 'Docker image name with version'
    value: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ steps.meta.outputs.version }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      env:
        DOCKER_METADATA_PR_HEAD_SHA: true
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: |
          type=match,pattern=${{ inputs.context }}\/(v[0-9]+.[0-9]+.[0-9]+),group=1
          type=sha
    - name: Build and push image
      id: push
      uses: docker/build-push-action@v6
      with:
        target: production
        context: ${{ inputs.context }}
        file: ${{ inputs.context }}/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        provenance: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
