version: '3.9'

services:
  nginx:
    image: "nginx:latest"
    restart: "unless-stopped"
    ports:
      - "${FORWARD_NGINX_PORT:-80}:80"
      - "${FORWARD_NGINX_PORT_SSL:-443}:443"
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./certbot/www:/var/www/certbot:ro"
    networks:
      - "default"

  certbot:
    image: "certbot/certbot:latest"
    restart: "unless-stopped"
    volumes:
      - "./certbot/conf:/etc/letsencrypt:rw"
      - "./certbot/www:/var/www/certbot:rw"

  nestjs:
    image: "ghcr.io/kishieel/men3-stack-backend:${NEST_VERSION:-latest}"
    restart: "unless-stopped"
    environment:
      DATABASE_URL: "${NEST_DATABASE_URL:-mysql://root:root@mysql:3306/app}"
    depends_on:
      - "mysql"
    networks:
      - "default"

  # nextjs:
  #   image: "ghcr.io/kishieel/men3-stack-frontend:${NEXT_VERSION:-latest}"
  #   restart: "unless-stopped"
  #   environment:
  #     NEXT_PUBLIC_API_URL: "${NEXT_PUBLIC_API_URL}"
  #     NEXT_PRIVATE_API_URL: "nestjs:3000"
  #   networks: [ "default" ]

  mysql:
    image: "mysql:8.3"
    restart: "unless-stopped"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "app"
    volumes:
      - "mysql-data:/var/lib/mysql"
    networks:
      - "default"

networks:
  default:
    driver: bridge

volumes:
  mysql-data:
    driver: local
